### ISSUE TITLE
Make maps Immutable

### ISSUE THREAD

**Issue by sandermangel** [KickAssCommerce/KickAssCommerce#5]
remove setters from maps. Is that even possible with the Symfony serializer?

**Comment by dmanners** [comment]
@sandermangel here is a list of things I love more than the Symfony serializer.

1. My wife,
2. My kids,
3. A good book,
4. Red wine,
5. Wildlife documentaries,
6. The MageStackDay team (of course having @sandermangel as my favorite)

As you can see this is a small list so I love the Symfony serializer. I know that we could remove the setters if the variables are public but I dont like that idea either. I will dive into the code and see if there is a way around this as immutable is always good.

**Comment by dmanners** [comment]
All "done" and merged!
